### ISSUE TITLE
Enabling ingress seems to generate a YAML parse error

### ISSUE THREAD

**Issue by philip-paystack** [halkeye-helm-charts/vouch#15]
When running the following:
`helm install vouch vouch/vouch --version 3.0.0 --set config.vouch.jwt.secret='foo' --set ingress.enabled=true`
I am seeing the following error:
`Error: YAML parse error on vouch/templates/ingress.yaml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context`

**Comment by philip-paystack** [comment]
> Is vouch my repo renamed?

Yes, running `helm repo list` yields
`vouch       	https://halkeye.github.io/helm-charts`

> Can you run helm template --debug with the same flags? I once had a report of an issue on one specific version of k8s but they closed the issue before we tracked it down

This is the output:
```
# Source: vouch/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vouch
  labels:
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/name: vouch
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/version: "0.32.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: vouch/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vouch
  labels:
    app.kubernetes.io/name: vouch
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/managed-by: Helm
stringData:
  config.yaml: |
    vouch:
      allowAllUsers: false
      domains: []
      jwt:
        secret: foo
      port: 9090
      testing: false
      whiteList: []
    oauth:
      callback_urls: []
      client_id: null
      client_secret: null
      preferredDomain: null
      provider: null
---
# Source: vouch/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vouch
  labels:
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/name: vouch
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/version: "0.32.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vouch
    app.kubernetes.io/instance: vouch
---
# Source: vouch/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vouch
  labels:
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/name: vouch
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/version: "0.32.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vouch
      app.kubernetes.io/instance: vouch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vouch
        app.kubernetes.io/instance: vouch
      annotations:
        checksum/secret: "136fb7a487ad71f6f77e45e73661c3203d22757ff9334c37eb7b8916d15a86fb"
    spec:
      serviceAccountName: vouch
      securityContext:
        {}
      containers:
        - name: vouch
          securityContext:
            {}
          image: "quay.io/vouch/vouch-proxy:0.32.0"
          command:
            []
          args:
            []
          imagePullPolicy: IfNotPresent
          env:
            - name: VOUCH_PORT
              value: "9090"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds:
            successThreshold:
            failureThreshold: 30
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
          resources:
            {}
      volumes:
      - name: config
        secret:
          secretName: vouch
      - name: data
        emptyDir: {}
---
# Source: vouch/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vouch
  labels:
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/name: vouch
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/version: "0.32.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            backend:
              service:
                name: vouch
                port:
                  name: http
            pathType: Prefix
---
# Source: vouch/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "vouch-test-connection"
  labels:
    app.kubernetes.io/name: vouch
    helm.sh/chart: vouch-3.0.0
    app.kubernetes.io/instance: vouch
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['vouch:9090']
  restartPolicy: Never
```
