### ISSUE TITLE
replicaCount parameter issue

### ISSUE THREAD

**Issue by bitchecker** [halkeye-helm-charts/vouch#42]
Hi,
I'm using this helm chart to deploy vouch on a Kubernetes cluster.

Everything works with the authentication backend system that I'm using, and I'm able to authenticate stuff. If I try to scale up the deployment to have high availability service, doesn't work anymore, and I'm not able anymore to log in into my application.

Is this a known design implementation, or it should work in every case?

**Comment by bitchecker** [comment]
```
config:
  vouch:
    [...]
    jwt:
      secret: 'xxxx'
    testing: false
```

with this config, replica set can be updated
