### ISSUE TITLE
Vouch not running via Helm

### ISSUE THREAD

**Issue by dmueller1607** [halkeye-helm-charts/vouch#9]
When running Vouch-Proxy (version 0.19.2 and 0.23.1 tested) using Helm Charts, I'm getting the following exception:

```
{"level":"fatal","ts":1618323472.0185509,"msg":"envconfig.Process: assigning VOUCH_PORT to Port: converting 'tcp://10.xx.xx.xx:9090' to type int. details: strconv.ParseInt: parsing \"tcp://10.xx.xx.xx:9090\": invalid syntax"}
```

**Comment by dmueller1607** [comment]
Here's my `values.yaml`:

```
replicaCount: 1

image:
  repository: "voucher/vouch-proxy"
  pullPolicy: IfNotPresent
  tag: "0.19.2"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9090
  internalPort: 9090

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 0
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
    periodSeconds: 10
  readiness:
    enabled: true
    initialDelaySeconds: 0
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
    periodSeconds: 10
  startup:
    enabled: true
    timeoutSeconds: 1
    successThreshold: 1
    initialDelaySeconds: 5
    failureThreshold: 30
    periodSeconds: 10

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: dev-system.company.net
      path: "/vouch(/|$)(.*)"
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

project: myproject

namespace: myproject

# vouch config
config:
  vouch:
    logLevel: debug
#    testing: false
#    listen: 0.0.0.0
#    port: 9090
    allowAllUsers: true
    headers:
      claims:
        - groups
    cookie:
      secure: false
      domain: company.net
  oauth:
    provider: adfs
    client_id: xxx
    client_secret: xxx
    auth_url: https://idp-test.company.net/nidp/oauth/nam/authz
    token_url: https://idp-test.company.net/nidp/oauth/nam/token
    user_info_url: https://idp-test.company.net/nidp/oauth/nam/userinfo
    scopes:
      – openid
      - microprofile-jwt
    callback_url: https://services-local.company.net/sso/auth


probes:
  liveness:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  startup:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

```
